// kbRead.mjs — "always read the KB" lookup helper.
//
// Usage:
//   node scripts/kbRead.mjs <topic...>          fuzzy match by block/entity/mechanic name
//   node scripts/kbRead.mjs --file <path>       find entries whose anchors cite that file
//   node scripts/kbRead.mjs torch --json        machine-readable output
//
// Protocol: run this BEFORE touching a block/entity/mechanic, then Read the
// printed entry files. Exit 0 on match, 1 on no match (meaning: create the
// entry from kb/_templates/entry.md per AGENTS.md before implementing).
import { readFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, relative, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const KB_ROOT = join(REPO_ROOT, "kb");
const INDEX_PATH = join(KB_ROOT, "index.json");

const IGNORE_DIRS = new Set(["_templates"]);
const IGNORE_FILES = new Set(["README.md", "index.json"]);

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      if (!IGNORE_DIRS.has(entry)) walk(full, out);
    } else if (st.isFile() && entry.endsWith(".md") && !IGNORE_FILES.has(entry)) {
      out.push(full);
    }
  }
  return out;
}

function norm(s) {
  return (s || "").toLowerCase().replace(/[^a-z0-9]/g, "");
}

function loadEntries() {
  const files = walk(KB_ROOT);
  const entries = [];
  for (const file of files) {
    const raw = readFileSync(file, "utf8");
    const fm = raw.match(/^---\n([\s\S]*?)\n---/);
    const body = raw.replace(/^---\n[\s\S]*?\n---\n/, "");
    const idM = raw.match(/^id:\s*(.+)$/m);
    const titleM = raw.match(/^title:\s*(.+)$/m);
    const statusM = raw.match(/^status:\s*(.+)$/m);
    const tagsM = raw.match(/^tags:\s*(.+)$/m);
    entries.push({
      file,
      rel: relative(KB_ROOT, file).split("\\").join("/"),
      id: (idM?.[1] || "").trim(),
      title: (titleM?.[1] || "").replace(/^["']|["']$/g, "").trim(),
      status: (statusM?.[1] || "").trim(),
      tags: (tagsM?.[1] || "").trim(),
      fm: fm?.[1] || "",
      body,
      raw,
    });
  }
  return entries;
}

function scoreEntry(e, terms, fileQ, indexedIds) {
  // Returns { score, reasons[] }. Higher wins.
  let score = 0;
  const reasons = [];
  const nTitle = norm(e.title);
  const nId = norm(e.id);
  const nTags = norm(e.tags);
  for (const t of terms) {
    if (!t) continue;
    if (nId === t) { score += 100; reasons.push(`id == ${t}`); }
    else if (nTitle === t) { score += 90; reasons.push(`title == ${t}`); }
    else if (nId.includes(t) && t.length >= 4) { score += 40; reasons.push(`id ~ ${t}`); }
    else if (nTitle.includes(t) && t.length >= 3) { score += 40; reasons.push(`title ~ ${t}`); }
    else if (t.includes(nTitle) && nTitle.length >= 4) { score += 30; reasons.push(`title in query`); }
    else if (nTags.includes(t) && t.length >= 3) { score += 20; reasons.push(`tag ~ ${t}`); }
    else if (norm(e.body).includes(t) && t.length >= 4) { score += 5; reasons.push(`body ~ ${t}`); }
  }
  if (fileQ) {
    if (indexedIds && indexedIds.has(e.id)) { score += 80; reasons.push(`code-index: cites ${fileQ}`); }
    const q = fileQ.toLowerCase();
    const hits = (e.body.match(/`([^`]+)`/g) || []).filter((a) => a.toLowerCase().includes(q));
    if (hits.length) { score += 60; reasons.push(`anchor cites ${fileQ} (${hits.length}x)`); }
    else if (e.body.toLowerCase().includes(q)) { score += 15; reasons.push(`mentions ${fileQ}`); }
  }
  return { score, reasons };
}

function main() {
  const argv = process.argv.slice(2);
  const asJson = argv.includes("--json");
  const fi = argv.indexOf("--file");
  const fileQ = fi >= 0 ? (argv[fi + 1] || "") : "";
  const terms = argv.filter((a, i) => !a.startsWith("--") && !(fi >= 0 && i === fi + 1)).map(norm).filter(Boolean);

  if (!existsSync(INDEX_PATH)) {
    console.error(`ERROR: ${relative(REPO_ROOT, INDEX_PATH)} missing — run node scripts/syncKbIndex.mjs`);
    process.exit(2);
  }
  if (!terms.length && !fileQ) {
    console.error("Usage: node scripts/kbRead.mjs <topic...> | --file <src/path> [--json]");
    console.error("  e.g. node scripts/kbRead.mjs torch");
    console.error("       node scripts/kbRead.mjs redstone lamp");
    console.error("       node scripts/kbRead.mjs --file src/game/terrain/biomes.ts");
    process.exit(2);
  }

  const entries = loadEntries();
  // Reverse index (generated by kbCoverage.mjs) answers --file directly;
  // live anchor scan below remains as fallback when the index is stale.
  let indexedIds = new Set();
  try {
    const ci = JSON.parse(readFileSync(join(KB_ROOT, "code-index.json"), "utf8"));
    const q = (fileQ || "").toLowerCase();
    if (q && ci.index) {
      for (const [f, ids] of Object.entries(ci.index)) {
        if (f.toLowerCase().includes(q)) for (const id of ids) indexedIds.add(id);
      }
    }
  } catch { /* no index yet — run npm run kb:check to generate it */ }
  const ranked = entries
    .map((e) => ({ e, ...scoreEntry(e, terms, fileQ, indexedIds) }))
    .filter((r) => r.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, 10);

  if (asJson) {
    console.log(JSON.stringify(ranked.map((r) => ({
      id: r.e.id, path: `kb/${r.e.rel}`, title: r.e.title,
      status: r.e.status, score: r.score, why: r.reasons,
    })), null, 2));
  } else if (!ranked.length) {
    console.log(`No KB entry matches "${terms.join(" ") || fileQ}".`);
    console.log("Per AGENTS.md: fetch https://minecraft.wiki/w/<Title>, create kb/<area>/<slug>.md");
    console.log("from kb/_templates/entry.md (or run: npm run kb:expand -- --write --limit 1), then implement.");
  } else {
    console.log(`KB matches for "${terms.join(" ") || fileQ}" (${ranked.length}):\n`);
    for (const r of ranked) {
      console.log(`- ${r.e.id} — ${r.e.title} [${r.e.status}]`);
      console.log(`    read: kb/${r.e.rel}   (${r.reasons.join("; ")})`);
    }
    console.log("\nRead the top entry file(s) before implementing; update anchors/deviations after.");
  }
  process.exit(ranked.length ? 0 : 1);
}

main();
