import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const KB_ROOT = join(REPO_ROOT, "kb");
const REGISTRY_PATH = join(REPO_ROOT, "catalog", "completeRegistry.json");
const REPORT_PATH = join(REPO_ROOT, "kb-wiki-report.md");

const API = "https://minecraft.wiki/api.php";
const DEFAULT_CATS = ["Blocks", "Java_Edition_blocks", "Items", "Entities", "Biomes"];

function norm(s) {
  return (s || "")
    .toLowerCase()
    .replace(/java edition /g, "")
    .replace(/[^a-z0-9]/g, "");
}

function loadRegistryNames() {
  if (!existsSync(REGISTRY_PATH)) return new Set();
  let reg;
  try { reg = JSON.parse(readFileSync(REGISTRY_PATH, "utf8")); } catch { return new Set(); }
  const set = new Set();
  for (const k in reg) {
    const n = reg[k].name;
    if (n) { set.add(norm(n)); set.add(norm(n).replace(/block$|item$/g, "")); }
  }
  return set;
}

function loadKbTokens() {
  const tokens = new Set();
  const stack = [KB_ROOT];
  const SKIP = new Set(["_templates", "node_modules", ".git"]);
  while (stack.length) {
    const dir = stack.pop();
    let entries;
    try { entries = require("node:fs").readdirSync(dir, { withFileTypes: true }); } catch { continue; }
    for (const e of entries) {
      if (SKIP.has(e.name)) continue;
      const full = join(dir, e.name);
      if (e.isDirectory()) stack.push(full);
      else if (e.name.endsWith(".md") && e.name !== "README.md" && e.name !== "index.json") {
        const raw = readFileSync(full, "utf8");
        const fm = raw.match(/^---\n([\s\S]*?)\n---/);
        if (!fm) continue;
        const raw2 = [fm[1]].join(" ");
        for (const piece of raw2.split(/[\s/_\-]+/)) {
          const t = norm(piece);
          if (t.length >= 3) tokens.add(t);
        }
        const titleM = raw.match(/^title:\s*(.+)$/m);
        if (titleM) for (const p of titleM[1].split(/\s+/)) { const t = norm(p); if (t.length >= 3) tokens.add(t); }
      }
    }
  }
  return tokens;
}

async function fetchCategory(cat) {
  const titles = [];
  let cmcontinue = "";
  do {
    const url = `${API}?action=query&format=json&list=categorymembers&cmtitle=Category:${encodeURIComponent(cat)}&cmlimit=500&cmtype=page${cmcontinue ? "&cmcontinue=" + encodeURIComponent(cmcontinue) : ""}`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status} for ${cat}`);
    const json = await res.json();
    const members = json.query?.categorymembers || [];
    for (const m of members) titles.push(m.title);
    cmcontinue = json.continue?.cmcontinue || "";
  } while (cmcontinue);
  return titles;
}

function matches(token, set) {
  if (!token) return false;
  for (const s of set) {
    if (s === token || (s.length >= 4 && (s.includes(token) || token.includes(s)))) return true;
  }
  return false;
}

async function main() {
  const fromFile = process.argv.includes("--from") ? process.argv[process.argv.indexOf("--from") + 1] : null;
  const catArg = process.argv.includes("--cat") ? process.argv[process.argv.indexOf("--cat") + 1] : null;
  const cats = catArg ? [catArg] : DEFAULT_CATS;

  let wikiTitles = [];
  if (fromFile) {
    wikiTitles = JSON.parse(readFileSync(fromFile, "utf8"));
    console.log(`Loaded ${wikiTitles.length} wiki titles from ${fromFile}`);
  } else {
    console.log(`Fetching categories from ${API} ...`);
    for (const c of cats) {
      try {
        const t = await fetchCategory(c);
        wikiTitles.push(...t);
        console.log(`  ${c}: ${t.length} pages`);
      } catch (e) {
        console.error(`  ${c}: FETCH FAILED (${e.message}) — skipping`);
      }
    }
  }

  const regNames = loadRegistryNames();
  const kbTokens = loadKbTokens();

  const seen = new Set();
  const noRegistry = [];
  const noKb = [];
  for (const title of wikiTitles) {
    const t = norm(title);
    if (!t || seen.has(t)) continue;
    seen.add(t);
    const inReg = matches(t, regNames);
    const inKb = matches(t, kbTokens);
    if (!inReg) noRegistry.push(title);
    else if (!inKb) noKb.push(title);
  }

  const md = [];
  md.push("# KB ↔ Minecraft Wiki reconciliation");
  md.push("");
  md.push(`_Generated by scripts/kbWiki.mjs — ${new Date().toISOString().slice(0, 10)}_`);
  md.push("");
  md.push(`Wiki pages scanned: **${seen.size}**`);
  md.push(`In registry (exists in game): ${seen.size - noRegistry.length}`);
  md.push(`Missing from registry entirely: **${noRegistry.length}**`);
  md.push(`In registry but undocumented in KB: **${noKb.length}**`);
  md.push("");
  md.push("## Wiki objects with NO registry entry (don't exist in the game at all)");
  md.push("");
  if (!noRegistry.length) md.push("_None._");
  else for (const t of noRegistry.sort()) md.push(`- ${t}`);
  md.push("");
  md.push("## In the game but undocumented in KB");
  md.push("");
  if (!noKb.length) md.push("_None._");
  else for (const t of noKb.sort()) md.push(`- ${t}`);
  md.push("");

  writeFileSync(REPORT_PATH, md.join("\n"));
  console.log(`\nReport: ${REPORT_PATH}`);
  console.log(`Missing from game: ${noRegistry.length}; undocumented: ${noKb.length}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
