import CDP from "chrome-remote-interface";
import { spawn } from "node:child_process";
import fs from "node:fs";
const chrome=spawn("/usr/bin/chromium",["--headless=new","--no-sandbox","--disable-dev-shm-usage","--enable-unsafe-swiftshader","--remote-debugging-port=9416","about:blank"],{stdio:"ignore"});
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
await sleep(1500);
const c=await CDP({port:9416}); const {Page,Runtime}=c; await Page.enable(); await Runtime.enable();
await Page.navigate({url:"http://127.0.0.1:5450/?sim=1"}); await sleep(8000);
const ev=async(expr)=>{const r=await Runtime.evaluate({expression:expr,returnByValue:true});return r.result?.value;};
const st=await ev(`(()=>{const api=window.__sim?.api; const s=window.__sim?.s;
  const a=api.stampEntity("pig",4,6); const b=api.stampEntity("chicken",12,6);
  s.player.x=8;s.player.y=65.4;s.player.z=8.4;s.player.yaw=0;s.player.pitch=-0.05;s.player.fly=true;
  s.uiPaused=false;s.active=true;s.time=6000;s.timeFlow=false;
  return { a: a ? JSON.stringify(a) : null, b: b ? JSON.stringify(b) : null };})()`);
console.log("spawn:", JSON.stringify(st));
await sleep(4000);
const d=await ev(`(()=>{const s=window.__sim?.s;const cv=s?.renderer?.domElement; cv&&s.renderer.render(s.scene,s.camera); return cv?cv.toDataURL("image/jpeg",0.9):null;})()`);
if(d) fs.writeFileSync("snapshots/eyes2.jpg", Buffer.from(d.split(",")[1],"base64"));
console.log("saved");
await c.close(); chrome.kill();
