import CDP from "chrome-remote-interface";
import { spawn } from "node:child_process";
const chrome=spawn("/usr/bin/chromium",["--headless=new","--no-sandbox","--disable-dev-shm-usage","--enable-unsafe-swiftshader","--remote-debugging-port=9413","about:blank"],{stdio:"ignore"});
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
await sleep(1500);
const c=await CDP({port:9413}); const {Page,Runtime}=c; await Page.enable(); await Runtime.enable();
const errs=[];
Runtime.exceptionThrown(p=>{const t=String(p.exceptionDetails?.exception?.description||p.exceptionDetails?.text||"").slice(0,500); errs.push(t);});
Runtime.consoleAPICalled(p=>{if(p.type==="error"){const m=p.args.map(a=>a.value??a.description??"").join(" ").slice(0,300); errs.push("console: "+m);}});
await Page.navigate({url:"http://127.0.0.1:5400/"}); await sleep(4000);
await Runtime.evaluate({expression:`(()=>{const btn=Array.from(document.querySelectorAll("button")).find(b=>b.innerText.toLowerCase().includes("quick play")); if(btn)btn.click(); return !!btn;})()`,returnByValue:true});
await sleep(7000);
await Runtime.evaluate({expression:`(()=>{const s=window.__sim?.s; if(!s)return; s.uiPaused=false; s.active=true; s.menuOpen=false; s.pauseOpen=false;
  s.player.x=-38.3; s.player.y=103; s.player.z=149.5; s.steering=true; return true;})()`,returnByValue:true});
await sleep(9000);
const r=await Runtime.evaluate({expression:`(()=>{const s=window.__sim?.s;
  return { f1: s.lastFrameAt, t1: s.time, scanT1: s.scanT, meshQ: s.meshQ.length, genQ: s.genQ.length };})()`,returnByValue:true});
await sleep(2500);
const r2=await Runtime.evaluate({expression:`(()=>{const s=window.__sim?.s;
  return { f2: s.lastFrameAt, t2: s.time, scanT2: s.scanT, meshQ: s.meshQ.length, genQ: s.genQ.length, calls: s.renderer?.info?.render?.calls };})()`,returnByValue:true});
console.log("s1:", JSON.stringify(r.result?.value));
console.log("s2:", JSON.stringify(r2.result?.value));
console.log("errors sample:", errs.slice(0,4).join("\n---\n") || "(none)");
await c.close(); chrome.kill();
